### PR TITLE
Explicitly use python2

### PR DESCRIPTION
**Pull request by Tranquility**
If the default python is set to 3 it fails.

### CODE REVIEW

**Comment by dnhgff** [comment]
first sci py, now static types, and you're telling me people have defaulted their pythons to 3? it is a brave new world :P

**Comment by Tranquility** [comment]
:smiley:

**Comment by Tranquility** [comment]
I just saw that you did not merge my commit but created your own with exactly the same change. Why did you do that?

**Comment by dnhgff** [comment]
i had not seen your fork until i had already pushed the fix

i generally assume that forks without prs are personal hotfixes. i would understand the intention to include your changes better if a pull request were sent

**Comment by Tranquility** [comment]
You are currently commenting in my pr ;)

**Comment by dnhgff** [comment]
haha, yikes, you are correct. total brain fart on my part

**Comment by dnhgff** [comment]
you will have to forgive me, this is my first time maintaining :P

**Pull request closed without merging**
